"use client";

import type { MicrositeData } from "@/lib/types";
import { HeroSection } from "./HeroSection";
import { ResearchFindings } from "./ResearchFindings";
import { ProofPoints } from "./ProofPoints";
import { ValueOpportunities } from "./ValueOpportunities";
import { ROICalculator } from "./ROICalculator";
import { PersonalizedUseCases } from "./PersonalizedUseCases";
import { ExecutiveNarrative } from "./ExecutiveNarrative";
import { DiscoveryQuestions } from "./DiscoveryQuestions";
import { SourcesAssumptions } from "./SourcesAssumptions";
import { MicrositeNav } from "./MicrositeNav";

interface MicrositeViewProps {
  data: MicrositeData;
}

export function MicrositeView({ data }: MicrositeViewProps) {
  return (
    <div className="min-h-screen bg-white">
      <MicrositeNav />
      <HeroSection data={data} />
      <ResearchFindings data={data} />
      <ProofPoints data={data} />
      <ValueOpportunities data={data} />
      <ROICalculator data={data} />
      <PersonalizedUseCases data={data} />
      <ExecutiveNarrative data={data} />
      <DiscoveryQuestions data={data} />
      <SourcesAssumptions data={data} />

      <footer className="bg-[#0a0a0a] border-t border-white/5 py-12 print:hidden">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 text-center">
          <p className="text-sm text-gray-500 mb-3">
            This microsite is not manually written. It is dynamically
            generated by an AI agent that researches the account, identifies
            strategic initiatives, checks for relevant Cognition/Devin
            proof points, maps them to Devin use cases, and builds a tailored
            ROI hypothesis.
          </p>
          <p className="text-xs text-gray-600">
            Generated on{" "}
            {new Date(data.generatedAt).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}{" "}
            &middot; Powered by Devin AI &middot; Built by Cognition
          </p>
        </div>
      </footer>
    </div>
  );
}
